image: ecr.aws.steedos.cn/dockerhub/steedos/gitpod-workspace-base:2.1

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: open-browser
    visibility: public
  - port: 6379
    onOpen: ignore
  - port: 27017
    onOpen: ignore
  - port: 5488 # jsreport-app
    onOpen: open-browser
    visibility: public
  - port: 1880 # node-red-app
    onOpen: open-browser
    visibility: public
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: MongoDB
    init: sh ./.scripts/setup.sh
    command: |
      mongod --replSet rs0 --dbpath /workspace/mongodb/data/db
  - command: |
      gp await-port 27017
      mongo steedos --eval "rs.initiate()"
      exit
  - name: Redis
    command: |
      redis-server --save "" --appendonly no --client-output-buffer-limit replica 0 0 0 --client-output-buffer-limit pubsub 0 0 0 --client-output-buffer-limit slave 0 0 0
  - name: Steedos
    init: |
      yarn install
    command: |
      sh ./.scripts/env.sh
      gp await-port 27017
      gp await-port 6379
      yarn start

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - redhat.vscode-yaml
    - steedos.steedosdx-vscode
    - steedos.steedosdx-vscode-core
    - ms-ceintl.vscode-language-pack-zh-hans
    - mongodb.mongodb-vscode
