env:
  PORT: 5000
  MONGO_URL: mongodb://127.0.0.1/steedos

cfs:
  store: "local"
  local: 
    folder: "./storage"
  aliyun:
    region: xxxxxx
    internal: false
    bucket: xxxxxx
    folder: xxxxxx
    accessKeyId: xxxxxx
    secretAccessKey: xxxxxx
  aws:
    region: xxxxxx
    bucket: xxxxxx
    folder: xxxxxx
    accessKeyId: xxxxxx
    secretAccessKey: xxxxxx



