env:
  PORT: 5000
  ROOT_URL: http://127.0.0.1:${PORT}/dzgy
  DB_SERVER: 127.0.0.1
  MONGO_URL: mongodb://${DB_SERVER}/steedos
datasources:
  default:
    connection:
      url: ${MONGO_URL}
    objectFiles: 
      - "../../apps/contracts/src/**"
public:
  cfs:
    store: "local"
    local:
      folder: "./storage"
cron:
  instancerecordqueue_interval: 10000
plugins: 
webservices:
  steedos: /
tenant: 
  _id: 