version: 2.1
jobs:
  build:
    working_directory: ~/electron-redux
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - electron-redux2-v3-{{ .Branch }}
            - electron-redux2-v3-
      - run:
          name: Install Dependencies
          command: yarn && yarn bootstrap
      - save_cache:
          key: electron-redux2-v3-{{ .Branch }}
          paths:
            - "~/.cache/yarn"
            - "~/electron-redux/node_modules"
            - "~/electron-redux/packages/electron-redux/node_modules"
            - "~/electron-redux/packages/electron-redux-e2e/node_modules"
      - run:
          name: Compile Assets
          command: yarn build
      - run:
          name: Run Tests
          command: yarn test
      - store_artifacts:
          path: ~/electron-redux/packages/electron-redux/dist
          destination: dist
      - store_artifacts:
          path: ~/electron-redux/packages/electron-redux/node_modules/coverage
          destination: coverage
