name: all
columns:
  - field: label
    wrap: false
  - field: name
    wrap: false
  - field: type
    wrap: false
  - field: query
    wrap: false
  - field: is_system
    wrap: false
filter_fields:
  - type
filter_scope: space
filters: []
label: 所有
scrolling_mode: standard
shared: true
show_count: false
type: grid
