contact_links:
  - name: Feature request
    url: https://github.com/tailwindlabs/play.tailwindcss.com/discussions/new?category=ideas
    about: 'Suggest any ideas you have using our discussion forums.'
